---
# - name: Download artifact from repository
#   get_url: >
#     url={{ teamserver_signed_artifact_url }}
#     dest=/var/lib/tomcat/webapps/Contrast.war
#   when: teamserver_deploy_enabled

# - name: Allow tomcat access to the war
#   file: >
#     path=/var/lib/tomcat/webapps/Contrast.war
#     state=touch
#     owner=tomcat
#     group=deployers
#   when: teamserver_deploy_enabled
