name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          apt-get install python-pip
          pip install ansible
          printf '[defaults]\nroles_path=../' >ansible.cfg
      - name: Basic role syntax check
        run:
          - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
